"""Добавлены скидки и размеры товаров в ProductVariant

Revision ID: 8d6be5ae0941
Revises: a67a09ddb768
Create Date: 2025-03-16 12:34:18.373128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6be5ae0941'
down_revision: Union[str, None] = 'a67a09ddb768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('size', sa.String(length=20), nullable=False))
    op.add_column('product_variants', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('product_variants', sa.Column('discount_percent', sa.Float(), nullable=False))
    op.drop_column('product_variants', 'variant')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_variants', sa.Column('variant', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('product_variants', 'discount_percent')
    op.drop_column('product_variants', 'color')
    op.drop_column('product_variants', 'size')
    # ### end Alembic commands ###
